theme: jekyll-theme-cayman
title: Louis Gobert Dev Project
google_analytics: G-D4RBV91XWQ

github:
  repository_url: fr/cv.html
  name: Curriculum vitæ






plugins:
  - jekyll-paginate
  - jekyll-sitemap