theme: jekyll-theme-cayman
title: Louis Gobert Dev Project
google_analytics: G-D4RBV91XWQ

github:
  repository_url: fr/cv.html
  title: Curriculum vitæ


navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"

plugins:
  - jekyll-paginate
  - jekyll-sitemap