# Generated by Django 2.2.18 on 2021-03-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210311_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.ImageField(blank=True, upload_to='img_folder/', verbose_name='Image'),
        ),
    ]
