# Generated by Django 2.2.18 on 2021-03-11 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210311_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlisted',
            field=models.ManyToManyField(blank=True, related_name='Watchlisted', to=settings.AUTH_USER_MODEL),
        ),
    ]
