# Generated by Django 2.2.18 on 2021-03-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_watchlisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watchlisted',
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to='auctions.Listing'),
        ),
    ]
