# Generated by Django 2.2.18 on 2021-03-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210312_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='date',
            new_name='publish_date',
        ),
    ]
