# Generated by Django 2.2.18 on 2021-03-12 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210312_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
