# Generated by Django 2.2.18 on 2021-03-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210312_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='publish_date',
        ),
    ]
