# Generated by Django 2.2.18 on 2021-03-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.ImageField(blank=True, upload_to='auctions/static/img_folder/', verbose_name='Image'),
        ),
    ]
