# Generated by Django 2.2.18 on 2021-04-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='squares',
            field=models.TextField(null=True),
        ),
    ]
