# Generated by Django 2.2.18 on 2021-04-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_api', '0003_auto_20210418_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='player_is_next',
            field=models.BooleanField(default=True),
        ),
    ]
