# Generated by Django 2.2.18 on 2021-04-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_api', '0004_board_player_is_next'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_piece_remain', models.IntegerField(default=16)),
                ('computer_piece_remain', models.IntegerField(default=16)),
                ('player_is_next', models.BooleanField(default=True)),
                ('board', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
