# Generated by Django 2.2.18 on 2021-04-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_api', '0006_auto_20210419_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='computer_piece_remain',
            new_name='piece_player_one',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player_piece_remain',
            new_name='piece_player_two',
        ),
    ]
