# Generated by Django 2.2.18 on 2021-04-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_api', '0007_auto_20210419_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.TextField(null=True),
        ),
    ]
