# Generated by Django 2.2.18 on 2021-04-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_api', '0008_auto_20210420_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_status',
            field=models.BooleanField(default=False),
        ),
    ]
